### ISSUE TITLE
Add terminal related functions (like term width, height) in libterm

### ISSUE THREAD

**Issue by CanadaHonk** [Electrux/Ethereal#1]
Is this still wanted? Could try and get something working.

**Comment by Chirag-Khandelwal** [comment]
Yes it is desired (stdlib/term.cpp), it would be awesome if you could work on that 😁

**Comment by CanadaHonk** [comment]
Only thing I don't get is adding funcs to the VM?

I see things like:
```c++
vm.funcs.add( { "colorize", 1,  1, { "str" }, FnType::MODULE, { .modfn = colorize }, true } );
```

But don't get what some of the parameters mean?

**Comment by CanadaHonk** [comment]
Currently have this:
```c++
#ifdef linux // For getting terminal size on Linux
#include <sys/ioctl.h>
#include <unistd.h>
#endif

...

var_base_t * term_width( vm_state_t & vm, func_call_data_t & fcd )
{
	#if linux
	struct winsize size;
	ioctl( STDOUT_FILENO, TIOCGWINSZ, &size );

	return new var_int_t(size.ws_row, fcd.args[ 0 ]->parse_ctr() );
	#endif
}

...

vm.funcs.add( { "term_width", 0, 0, {}, FnType::MODULE, { .modfn = term_width }, true } );
```

**Comment by Chirag-Khandelwal** [comment]
see line 41 `src/VM/Functions.hpp` the `function_t` struct. Ask up if something is not understood 😁

Also, if you are going to create a new object and return it, u should set the last field (`manual_res_free`) of the struct to be `true`, and to `false` if you are returning an already existing object.
`vm.nil` is an exception here because the interpreter treats it specially. So, even if you return newly created objects, you can still return nil without having to set the last struct field to be false (since nil already exists).

**Comment by CanadaHonk** [comment]
With returning variables do I need to:
```c++
return new var_int_t(size.ws_row, fcd.args[ 0 ]->parse_ctr() );
```

Or can I just do:
```c++
return size.ws_row;
```

Looking through the other modules it would seem you need to do the earlier.

**Comment by CanadaHonk** [comment]
Just built it, built fine and all tests passed. Will actually try it out now.

**Comment by CanadaHonk** [comment]
Need to add Windows support after anyways.

**Comment by CanadaHonk** [comment]
Seems to not work, when adding this line to the `mod_term.et` test, I get a segfault:
```c++
println( term_width() );
```

**Comment by CanadaHonk** [comment]
Still get a segfault if in the term module I have this:
```c++
return new var_int_t(size.ws_row, 0 );
```

**Comment by Chirag-Khandelwal** [comment]
well, windows support is not built into the language right now anyway, so u can skip that part if you desire.
Also, tests do not include the feature you built so use your feature first. Only then will you know if it works or not.
Finally, for returning, you will have to do the `return new` thing since it is a new variable in the perspective of the language.

**Comment by CanadaHonk** [comment]
What do you mean about that thing about testing?

After changing the code of Ethereal and then the test, I run `./bootstrap.sh`, then `./perform_tests.et`. Surely that would work fine?

**Comment by Chirag-Khandelwal** [comment]
that would work,yes, assuming u added ur function in one of the files in tests/ directory.

**Comment by CanadaHonk** [comment]
Right now I get a seg fault whenever I run the function (below):
```c++
var_base_t * term_width( vm_state_t & vm, func_call_data_t & fcd )
{
	#if linux
	struct winsize size;
	ioctl( STDOUT_FILENO, TIOCGWINSZ, &size );

	return new var_int_t( size.ws_row, fcd.args[ 0 ]->parse_ctr() );
	#endif
}
```

**Comment by CanadaHonk** [comment]
Registration code (at the bottom of `REGISTER_MODULE ( term )`:
```c++
vm.funcs.add( { "term_width", 0, 0, {}, FnType::MODULE, { .modfn = term_width }, true } );
```

**Comment by Chirag-Khandelwal** [comment]
fcd.args is available when the function u fired gets some arguments, otherwise it is empty. So, u accessing args[0] will fail

**Comment by CanadaHonk** [comment]
Should I just pass `0` or something as the 2nd var?

**Comment by CanadaHonk** [comment]
I think it was because:
`#if linux` would never run the code inside it, it needed to be `#if __linux__`

**Comment by CanadaHonk** [comment]
I got it working!

**Comment by CanadaHonk** [comment]
Is now accessible via `term.width`

**Comment by CanadaHonk** [comment]
I'm going to add `term.height` now, and probably `term.size` which contains both as well.

**Comment by CanadaHonk** [comment]
How do you properly make a `var_tuple_t`? Is there any way to produce it from a proper / real tuple?

**Comment by CanadaHonk** [comment]
I've given up on size (`term.size`) for now. `term.width` (plus `term_width()`) and `term.height` (plus `term_height()` are fully functional.

**Comment by Chirag-Khandelwal** [comment]
for tuple,
```
import tuple;
tup = make_tuple( /* all tuple elements */ );
println( 'first element: ', tup.0 );
```

**Comment by Chirag-Khandelwal** [comment]
i will work on term.size when i reach home 😃

**Comment by Chirag-Khandelwal** [comment]
Okay, I have updated the code base so `fcd.args[..]->parse_ctr()` will no longer be required as an argument for creating new variables. And by the way, for your code, term width should use `ws_col` struct member shouldn't it?

**Comment by Chirag-Khandelwal** [comment]
Where are u performing all these additions? When you are done please do share them :)
Also, what exactly do you mean by term size? I seem to have that confused haha.

**Comment by CanadaHonk** [comment]
Sorry, didn't see. Added in `stdlib/term.cpp` and `include/ethereal/term.et`, I also added some `println` of the size in `tests/mod_term.et`.

By size I mean probably a tuple.

I'll push ASAP.

**Comment by Chirag-Khandelwal** [comment]
Oh, alright. Also, you cannot simply push to this repository. You will have to fork it, modify there, and then create a pull request for me to merge :)

**Comment by Chirag-Khandelwal** [comment]
and, for using a tuple, you can create a vector of `var_base_t *` and push the row and column in it. Then create a `var_tuple_t` with that vector and return that.
But then you will have to access the row and column using `size.0` and `size.1`

**Comment by Chirag-Khandelwal** [comment]
Another way would be to create a struct in `include/ethereal/term.et` and return that struct from a `term_size()` function. Then you can use `size.row` and `size.col` struct members

**Comment by Chirag-Khandelwal** [comment]
I wrote the terminal size functions/structs (thanks to you). You can see the commit if you want :)
Reopen if you need to.
