### ISSUE TITLE
Fix / update README.md in VSCode extension

### ISSUE THREAD

**Issue by CanadaHonk** [Electrux/Ethereal#2]
Currently standard / default, would be quite easy to update. I can do it if wanted.

**Comment by Chirag-Khandelwal** [comment]
I'd really appreciate it if you could
if not, i'll do it as soon as i can 😊

**Comment by Chirag-Khandelwal** [comment]
Okay fixed this in a5944edbf45714a06b34e7290115cf78317b828e.
Please see if there are any changes that need to be done, if not, close the issue.
Thanks :)

**Comment by Chirag-Khandelwal** [comment]
Reopen if needed :)
