### ISSUE TITLE
Can't add / '+' a string and an int

### ISSUE THREAD

**Issue by CanadaHonk** [Electrux/Ethereal#3]
Surely it should convert the int to a string and concat / merge them? But I'm not sure.

**Comment by Chirag-Khandelwal** [comment]
no it doesn't convert to string implicitly, to do that u will have to convert int to string first and then u can concat them.
to convert int to string, u can do the following:
```
5.to_str()

```

**Comment by CanadaHonk** [comment]
Shouldn't it happen automatically though? At least most other langs do.

**Comment by CanadaHonk** [comment]
Think it would be pretty easy to add the `+` operator in the `str` module. I can do it now if you want.

**Comment by CanadaHonk** [comment]
Can't figure out how to do it lol. Leaving it for now.

**Comment by Chirag-Khandelwal** [comment]
Well, it's ok. I shall perhaps do it. Although I do feel it to be not too useful

**Comment by Chirag-Khandelwal** [comment]
to_str() converts any type to string so it should be just fine, although i can make a short hand style for it maybe.
how about something like...
`str( /* anything */ )`?

**Comment by CanadaHonk** [comment]
Yeah maybe.

**Comment by CanadaHonk** [comment]
Also I have a weird bug.

I have this script:
```c++
println( 'height: ' + term.height.to_str() );
```

But it errors out when I run it with:
```
mod_term.et 11[20]: error: function with name '+' and arg count 2 (str, str) does not exist
println( 'width: ' + term.width.to_str() );
```

**Comment by CanadaHonk** [comment]
I reverted all my changes to do with operators and strings fyi.

**Comment by Chirag-Khandelwal** [comment]
Did you `import str;`? Also, for println, you can just pass all arguments using comma separation instead of manually concatenating the strings.

**Comment by CanadaHonk** [comment]
Oh haha, I didn't import it. Thanks for the tip as well.

**Comment by Chirag-Khandelwal** [comment]
No problem :)
I wonder if I should just add the string concatenation, append, and comparison functions in the core module...

**Comment by CanadaHonk** [comment]
Starting work on it again now.

**Comment by Chirag-Khandelwal** [comment]
okay, good luck

**Comment by Chirag-Khandelwal** [comment]
I think I will not let a string and any other type be added directly. This is because someone may accidentally concatenate two variables if they don't know one of them is string (which is entirely possible due to the dynamically typed nature of the language).
I shall consider more on this, but for now, I'll close this issue. Thanks! :)
