### ISSUE TITLE
Create a CMake/Make build script

### ISSUE THREAD

**Issue by Chirag-Khandelwal** [Electrux/Ethereal#7]
It would be really good to have a CMake script or Makefile for building the language. It needs to be identical to the `bootstrap.sh` script located in the main repository.

Any help is much appreciated! ❤️

**Comment by IQBigBang** [comment]
I'd like to help

**Comment by Chirag-Khandelwal** [comment]
That's awesome! I'll assign it to you then. I'd be glad to help if needed but I don't know Cmake/make syntax 😅

**Comment by Chirag-Khandelwal** [comment]
Has been finished for now with commits 58d852fb through 0d66faf2
